### PR TITLE
Install configparser only for Python < 3.5

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by cthoyt** [comment]
Hi Nicola, 

I was under the impression that installing the `configparser` module when on python3 didn't really do anything, since it is a backport. We're just using it for python2 backwards compatibility because we need it to parse BELANNO and BELNS files.

Can you explain why py35 is your cutoff for when we shouldn't do that?

-Charlie

**Comment by nsoranzo** [comment]
@cthoyt The reasons for the patch are:
- in general, we should not install something that's not required
- I'm working on a Conda package for PyBEL and the conda-forge package for `configparser` is only available for Python 2.7 and 3.4.

The last release of configparser is [3.5.0](https://pypi.python.org/pypi/configparser/3.5.0) and contains the updated configparser from Python 3.5 (as its version implies). To use it under Python 3.x, the syntax:
```
from backports import configparser
```
should be used. The only feature added after Python 3.3 is the `converters` argument for `configparser.ConfigParser()`, which pybel does not use. So probably a better fix would be using:
```
if sys.version_info < (3, ):
```

**Comment by cthoyt** [comment]
That's a great point! Thanks for explaining. I have a couple more tweaks to make then I'll slice 0.4.1 with this.

**Comment by nsoranzo** [comment]
Thanks for the fast merge! Are you going to change the `if` as in my comment above?

**Comment by cthoyt** [comment]
I'll give it a shot and see how the build on Travis does. we're checking with 27, 34, 35, and 36 so if there's a problem it will catch it.

**Comment by cthoyt** [comment]
It looks like everything is still okay with the more general version checking!

**Pull request merged**
