### PR TITLE
Use SQL instead of Python for iterate_singleton_edges_from_network.

### PR DESCRIPTION
**Pull request by scolby33**

### CODE REVIEW

**Comment by cthoyt** [comment]
1. I think I wrote tests for this function. Are they still there?

2. The original purpose of this function was to find all these Singleton edges then drop them. Want to write another function that does that?

**Comment by scolby33** [comment]
Yes, the test is here; it passes. https://github.com/pybel/pybel/blob/23e049d352072c2aed752ed3191956725f0a62c4/tests/test_manager/test_manager_drop.py#L92-L96

Drop edges that only belong to one network? Why would you do that?

**Comment by cthoyt** [comment]
An edge might belong to multiple
Networks. When I drop a given network, I need to find the edges that only belong to that network (and not other) and drop those too

**Comment by scolby33** [comment]
Oh that obviously makes sense; I envisioned your original comment as like some check you did on a regular basis, not a specific cleanup.

That's definitely doable if you point me to where Networks are deleted; it should be done in the same transaction.

**Comment by scolby33** [comment]
Actually, it shouldn't be a function that even returns a Python iterable, it should just do the drop itself.

(If you're looking for max SQL use; bringing it through Python is probably not terrible.)

**Comment by cthoyt** [comment]
So we can go ahead and reorganize the code - there's no strict need for being able to iterate over singleton edges. The real important thing to solve is actually an issue I already opened (#270) to make dropping networks (and their associated edges that don't also appear in other networks) more efficient.

https://github.com/pybel/pybel/blob/664b906579b3c149afd03d5e0ef888f6e603d5e8/src/pybel/manager/cache_manager.py#L653-L676

**Comment by scolby33** [comment]
http://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.delete

This seems like what we want, assuming we don't have the CASCADE issues they mention a little down the page. What do you think about that?

**Comment by scolby33** [comment]
For `drop_networks` you would want *all* edges dropped?

**Comment by scolby33** [comment]
Superseded by #319.

**Pull request closed without merging**
